# Generated by Django 5.1.5 on 2025-04-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_name',
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='Unnamed Car', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='speed',
            field=models.IntegerField(default=50),
        ),
    ]
